var1 = "메롱"
var2 = 456
var3 = 789


act1 :
	echo "안녕하세요"
	echo "두번째 문장"

act2 :
	echo ${var1}

act3 : 피츄
	echo "피까 ?"

라이츄 : 피카츄 번개의돌
	echo "피카츄가 라이츄로 진화했다!!"

피츄 :
	echo "피피츄츄"

번개의돌 :
	echo "내가 찐"



# 조건문에서 파일보다 함수를 먼저 확인할 것
.PHONY : 번개의돌